import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import { AppShell, Text, TextInput } from '@mantine/core';
import { MyHeader } from '../components/Header';
import { Nav } from '../components/Nav';
import { VideoList } from '../components/VideoList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>YouTube Video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        // navbar={<Nav />}
        header={<MyHeader />}
      >
        <VideoList />

      </AppShell>
    </div>
  )
}

export default Home
